version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data://var/lib/postgresql/data

  backend:
    build:
      context: exhibition_of_kittens
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static://app/static_django/
      - media://app/media/
