# Generated by Django 4.2.16 on 2024-10-01 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('color', models.CharField(max_length=16, verbose_name='Цвет')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Возраст (полных месяцев)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(default=None, null=True, upload_to='kittens/images/', verbose_name='Фото')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kittens', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Котенок',
                'verbose_name_plural': 'Котята',
            },
        ),
    ]
