# Generated by Django 4.2.16 on 2024-10-04 13:09

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens', '0004_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitten',
            options={'default_related_name': 'kittens', 'ordering': ('-pub_time',), 'verbose_name': 'Котенок', 'verbose_name_plural': 'Котята'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'default_related_name': 'scores', 'ordering': ('-pub_time',), 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AddField(
            model_name='kitten',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 4, 13, 8, 43, 914637, tzinfo=datetime.timezone.utc), verbose_name='Время публикации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 4, 13, 8, 43, 914637, tzinfo=datetime.timezone.utc), verbose_name='Время публикации'),
            preserve_default=False,
        ),
    ]
